site_name: IVAC2 EBBU FIRDEF Manual
pages:
    - Home: index.md
theme: 'united'

# Pages   
pages:
  - Home: index.md
  - Labels:
    - Introduction: labels/introduction.md
    - Label Symbols: labels/labelsymbols.md
    - Ground Labels: labels/groundLabels.md
    - Airborne Labels: labels/airbornelabels.md
    - Label Indicators: labels/labelindicators.md
  - Presets:
    - Introduction: presets/introduction.md
    - List of presets: presets/list.md

# Other
repo_url: https://github.com/Diesel8/IVAC2-EBBU-FIRDEF-MANUAL/
edit_uri: edit/master/docs/
site_author: Jessy Stas
copyright: 'Copyright &copy; 2017 Jessy Stas'




